export const VIDEO_SOURCE_CHAT_COPY = {
  zh: {
    model: '选择问答模型',
    defaultModel: '默认（助手配置）',
    modelsUnavailable: '模型列表暂不可用，请重新打开重试',
    unavailable: '视频暂时无法加载，可重试或在原站打开。',
    originalLink: '原视频链接',
    preparing: '正在准备视频播放…',
    retry: '重试加载视频',
    more: '更多分析',
    summary: '已保存的语音摘要',
    empty: '在这里提问视频内容，回答会引用对应的字幕时间码。',
    placeholder: '针对这个视频提问…',
    send: '发送',
    details: '问答说明',
    disclosure: '依据当前资料回答，使用所选模型并按当前通道计费。回答随资料保存。'
  },
  'zh-hant': {
    model: '選擇問答模型',
    defaultModel: '預設（助手設定）',
    modelsUnavailable: '模型清單暫時無法使用，請重新開啟重試',
    unavailable: '影片暫時無法載入，可重試或在原站開啟。',
    originalLink: '原影片連結',
    preparing: '正在準備影片播放…',
    retry: '重試載入影片',
    more: '更多分析',
    summary: '已儲存的語音摘要',
    empty: '在這裡提問影片內容，回答會引用對應的字幕時間碼。',
    placeholder: '針對這部影片提問…',
    send: '傳送',
    details: '問答說明',
    disclosure: '依據目前資料回答，使用所選模型並依目前通道計費。回答隨資料儲存。'
  },
  en: {
    model: 'Choose answer model',
    defaultModel: 'Default (Agent settings)',
    modelsUnavailable: 'Models unavailable. Reopen to retry.',
    unavailable: 'Video could not be loaded. Retry or open the original site.',
    originalLink: 'Original video link',
    preparing: 'Preparing video playback…',
    retry: 'Retry video',
    more: 'More analysis',
    summary: 'Saved audio summary',
    empty: 'Ask about this video here. Answers cite the corresponding transcript timestamps.',
    placeholder: 'Ask about this video…',
    send: 'Send',
    details: 'About answers',
    disclosure:
      'Answers use this source and your selected model, billed through the current channel. Answers are saved with the source.'
  },
  ja: {
    model: '回答モデルを選択',
    defaultModel: '既定（助手の設定）',
    modelsUnavailable: 'モデル一覧を取得できません。開き直して再試行してください。',
    unavailable: '動画を読み込めません。再試行するか元のサイトで開いてください。',
    originalLink: '元の動画リンク',
    preparing: '動画の再生を準備中…',
    retry: '動画を再読み込み',
    more: 'その他の分析',
    summary: '保存した音声の要約',
    empty: 'ここで動画の内容を質問できます。回答には文字起こしのタイムコードが引用されます。',
    placeholder: 'この動画について質問…',
    send: '送信',
    details: '回答について',
    disclosure:
      '現在の資料に基づき、選択したモデルで回答します。現在の接続経路で課金され、回答は資料とともに保存されます。'
  },
  ar: {
    model: 'اختر نموذج الإجابة',
    defaultModel: 'الافتراضي (إعدادات المساعد)',
    modelsUnavailable: 'النماذج غير متاحة. أعد الفتح للمحاولة مجددًا.',
    unavailable: 'تعذر تحميل الفيديو. أعد المحاولة أو افتح الموقع الأصلي.',
    originalLink: 'رابط الفيديو الأصلي',
    preparing: 'جارٍ تجهيز تشغيل الفيديو…',
    retry: 'إعادة تحميل الفيديو',
    more: 'المزيد من التحليل',
    summary: 'ملخص الصوت المحفوظ',
    empty: 'اسأل عن هذا الفيديو هنا. تستشهد الإجابات بالتوقيت المقابل في النص.',
    placeholder: 'اسأل عن هذا الفيديو…',
    send: 'إرسال',
    details: 'حول الإجابات',
    disclosure:
      'تستند الإجابات إلى هذا المصدر وتستخدم النموذج المحدد مع احتساب التكلفة عبر القناة الحالية. تُحفظ الإجابات مع المصدر.'
  }
} as const
