/**
 * apex-relay-key-anchors.ts
 *
 * THE single source of truth for "where the ApexNodes managed relay key lives
 * in config.yaml", plus the two operations that keep every one of those places
 * agreeing: a registry-driven writer and a registry-INDEPENDENT auditor.
 *
 * ── Why this module exists (hc-602) ─────────────────────────────────────────
 * The same bug has now been shipped twice. hc-592 healed the `moa` entry to the
 * relay and missed the `custom + empty base_url` entry; hc-595 healed
 * `model.api_key` and missed `custom_providers[].api_key`. Both times the fix
 * covered the exit that had been *observed* and left the others behind, and both
 * times the user saw the identical symptom (the model catalog collapsing to the
 * single hard-coded model) come straight back.
 *
 * hc-595's specific miss is worth writing down, because it is the whole reason
 * this file is structured the way it is. Its patcher collected `custom_providers`
 * list entries with `/^- /` — a list lead at COLUMN 0 — while this app's own
 * seeder (`managedModelConfigYaml`) emits `  - name: …` at a two-space indent.
 * The patcher could not see the entries its own writer had produced, so on every
 * real install `entries.matched` was 0. It reported success anyway, for two
 * compounding reasons:
 *   - `matched` was true because the *other* anchor (`model:`) had matched, and
 *   - the read-back verification re-ran THE SAME PARSER, so the parser's blind
 *     spot verified its own blind spot.
 * The hc-595 unit tests passed because their fixture was hand-written to the
 * parser's shape rather than generated by the producers.
 *
 * ── The three rules that follow from that ───────────────────────────────────
 * 1. ONE registry. `MANAGED_KEY_ANCHORS` below is the complete list of places a
 *    managed relay key may live. The writer iterates it; the invariant test
 *    iterates it. A new anchor is one entry here and is then covered
 *    automatically — there is no second list to remember.
 * 2. ONE parser, and it is a real one. `parseYamlMaps` walks the document by
 *    indentation instead of pattern-matching the shapes we happened to think of,
 *    so "our writer emits a shape our reader cannot see" is not expressible.
 * 3. The verifier does NOT reuse the writer's judgement.
 *    `auditManagedRelayKeyAnchors` never looks at the registry: it flags EVERY
 *    map in the document that both carries an `api_key` and points at the relay.
 *    An anchor nobody registered is therefore still caught — as a loud audit
 *    failure rather than a silent stale credential.
 *
 * Electron-free and dependency-free (same contract as its siblings), so all of
 * it is unit-testable with `vitest run --project electron`.
 */
import { createHash } from 'node:crypto'

// Display name of the relay's registered endpoint entry. Seeded by the desktop
// and used as a secondary identity match: a PyYAML re-dump that rewrites or
// drops `base_url` must not make our own entry unrecognizable.
const MANAGED_PROVIDER_NAME = 'Apex-nodes.com'

// ── YAML reading (indentation walk, no dependency) ──────────────────────────

interface YamlField {
  /** 0-based index into the source lines. */
  line: number
  /** Scalar value with surrounding quotes removed; '' when the key opens a block. */
  value: string
}

/** One mapping node in the document, addressed by a dotted/indexed path. */
export interface YamlMap {
  /** '' for the document root, else e.g. `model`, `custom_providers[0]`, `providers.apex`. */
  path: string
  /** Column at which this map's keys are written. */
  indent: number
  fields: Record<string, YamlField>
  /** Last line that belongs to this map — where a missing key gets inserted. */
  lastLine: number
}

/** Strip one layer of matching quotes from a scalar. */
function unquote(value: string): string {
  const trimmed = String(value ?? '').trim()
  const match = trimmed.match(/^(["'])([\s\S]*)\1$/)

  return match ? match[2] : trimmed
}

/**
 * Walk `raw` and return every mapping node in it, keyed by path.
 *
 * Deliberately a *structural* walk rather than a set of targeted regexes: the
 * caller asks "which maps are there and what fields do they hold", and gets the
 * same answer for `custom_providers:\n- k: v` and `custom_providers:\n  - k: v`
 * and a `providers:` dict, because indentation is the only thing being read.
 * That is the property hc-595 lacked.
 *
 * Not a general YAML parser — it understands block mappings, block sequences and
 * scalars, which is all config.yaml is. Block scalars (`|` / `>`) are skipped
 * wholesale so their free text can never be mistaken for keys.
 */
export function parseYamlMaps(raw: string): { lines: string[]; maps: YamlMap[] } {
  // CRLF-tolerant. The runtime saves config.yaml with
  // `os.fdopen(fd, "w", encoding="utf-8")` (utils.py::atomic_yaml_write) — text
  // mode with no `newline=`, so on WINDOWS every line ends `\r\n`. A trailing
  // `\r` is a line terminator to JS regex, so `(.*)$` cannot match past it and a
  // naive `split('\n')` finds NO fields at all: on Windows the entire relay-key
  // sync silently degrades to `no-managed-anchor`. Splitting on `/\r?\n/` here
  // (and restoring the file's own ending on write) is what makes this the same
  // code path on all three platforms.
  const lines = String(raw ?? '').split(/\r?\n/)
  const root: YamlMap = { path: '', indent: 0, fields: {}, lastLine: -1 }
  const maps: YamlMap[] = [root]

  interface Scope {
    kind: 'map' | 'seq' | 'pending'
    path: string
    /** Column of this container's entries; -1 while still unresolved. */
    indent: number
    /** Indent of the `key:` line that opened a pending container. */
    openerIndent: number
    map: YamlMap | null
    count: number
  }

  const stack: Scope[] = [{ kind: 'map', path: '', indent: 0, openerIndent: -1, map: root, count: 0 }]
  // Indent of an open block scalar (`|` / `>`); everything deeper is its text.
  let blockScalarIndent = -1

  const keyOf = (path: string, name: string) => (path ? `${path}.${name}` : name)

  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i]

    if (!line.trim() || /^\s*#/.test(line)) {continue}

    const lead = line.match(/^(\s*)(-\s+)?/) as RegExpMatchArray
    const markerIndent = lead[1].length
    const isItem = Boolean(lead[2])
    const contentIndent = markerIndent + (lead[2] ? lead[2].length : 0)

    if (blockScalarIndent >= 0) {
      if (markerIndent > blockScalarIndent) {continue}
      blockScalarIndent = -1
    }

    // Close every container this line has dedented out of, and resolve the shape
    // of a container that was opened by a `key:` line but has not seen a child.
    for (;;) {
      const top = stack[stack.length - 1]

      if (!top || stack.length === 1) {break}

      if (top.kind === 'pending') {
        const isChild = isItem ? markerIndent >= top.openerIndent : markerIndent > top.openerIndent

        if (!isChild) {
          stack.pop()

          continue
        }

        if (isItem) {
          top.kind = 'seq'
          top.indent = markerIndent
        } else {
          top.kind = 'map'
          top.indent = markerIndent
          top.map = { path: top.path, indent: markerIndent, fields: {}, lastLine: i }
          maps.push(top.map)
        }

        break
      }

      // A map entry lives at exactly its map's indent; anything shallower is out.
      if (top.kind === 'map' && markerIndent < top.indent) {
        stack.pop()

        continue
      }

      // A sequence only holds `- ` items at its own indent.
      if (top.kind === 'seq' && (!isItem || markerIndent < top.indent)) {
        stack.pop()

        continue
      }

      break
    }

    const top = stack[stack.length - 1]

    if (top.kind === 'seq') {
      const rest = line.slice(contentIndent)
      const index = top.count
      top.count += 1

      // A scalar item (`- copilot`) holds no fields — nothing to address.
      if (!/^[A-Za-z0-9_.$-]+:(\s|$)/.test(rest)) {continue}

      const itemMap: YamlMap = {
        path: `${top.path}[${index}]`,
        indent: contentIndent,
        fields: {},
        lastLine: i
      }

      maps.push(itemMap)
      stack.push({
        kind: 'map',
        path: itemMap.path,
        indent: contentIndent,
        openerIndent: markerIndent,
        map: itemMap,
        count: 0
      })
    }

    const scope = stack[stack.length - 1]

    if (scope.kind !== 'map' || !scope.map) {continue}

    const entry = line.slice(contentIndent).match(/^([A-Za-z0-9_.$-]+):\s*(.*)$/)

    if (!entry) {continue}

    const name = entry[1]
    const rawValue = entry[2].trim()
    scope.map.fields[name] = { line: i, value: unquote(rawValue) }
    scope.map.lastLine = i

    if (rawValue === '|' || rawValue === '>' || /^[|>][-+\d]*$/.test(rawValue)) {
      blockScalarIndent = contentIndent

      continue
    }

    // An empty value opens a nested block; a comment-only tail counts as empty.
    if (rawValue === '' || /^#/.test(rawValue)) {
      stack.push({
        kind: 'pending',
        path: keyOf(scope.path, name),
        indent: -1,
        openerIndent: contentIndent,
        map: null,
        count: 0
      })
    }
  }

  return { lines, maps }
}

// ── Relay identity helpers ──────────────────────────────────────────────────

const trimSlashes = (value: string) => String(value ?? '').trim().replace(/\/+$/, '')

const hostOf = (url: string) =>
  (String(url ?? '').match(/^[a-z][a-z0-9+.-]*:\/\/([^/?#]+)/i) || ['', ''])[1].toLowerCase()

/** The URL field of an endpoint map: `base_url` (legacy list) or `api` (v12 dict). */
function endpointUrl(map: YamlMap): string {
  return map.fields.base_url?.value ?? map.fields.api?.value ?? ''
}

/**
 * True when `map` is our registered relay endpoint. `base_url`/`api` is the
 * primary identity; the seeded NAME is the fallback, because a runtime re-dump
 * that rewrites the URL path (`…/relay` vs `…/relay/v1`) would otherwise orphan
 * our own entry — but only on the same host, so a genuinely different endpoint
 * that happens to carry the name is never handed a relay key.
 */
function pointsAtRelay(map: YamlMap, baseUrl: string): boolean {
  const url = endpointUrl(map)

  if (url && trimSlashes(url) === trimSlashes(baseUrl)) {return true}
  const name = map.fields.name?.value ?? ''

  if (name.toLowerCase() !== MANAGED_PROVIDER_NAME.toLowerCase()) {return false}
  const host = hostOf(url)

  return !host || host === hostOf(baseUrl)
}

/**
 * A relay key rendered safe for a log line, a test assertion or a PR: the scheme
 * prefix plus a truncated digest. Never emit the raw key — config.yaml surgery
 * and the self-heal both log a lot, and desktop logs travel (support bundles,
 * screenshots, this repo's public PRs).
 */
export function maskRelayKey(key: string): string {
  const value = String(key ?? '').trim()

  if (!value) {return '(none)'}
  const digest = createHash('sha256').update(value).digest('hex').slice(0, 16)

  return `${value.slice(0, 3)}…#${digest}`
}

// ── The anchor registry ─────────────────────────────────────────────────────

export interface ManagedKeyAnchorKind {
  /** Stable id — appears in logs, audit output and the invariant test. */
  id: string
  /** Why this place holds a relay key, and what breaks when it goes stale. */
  why: string
  /** True when `map` is this kind of managed relay anchor. */
  matches: (map: YamlMap, baseUrl: string) => boolean
}

/**
 * EVERY place a managed relay key lives in config.yaml.
 *
 * ⚠️ Adding a new one? Add it HERE and nowhere else. The writer, the log line
 * and the class-level invariant test all iterate this array, so a registered
 * anchor is covered everywhere the moment it is listed. An anchor that is NOT
 * listed is not written — and `auditManagedRelayKeyAnchors` (which never reads
 * this array) will fail the write and the test until it is.
 *
 * Deliberately NOT anchors, recorded so the next reader does not have to
 * re-derive it:
 *   - `moa.presets.*` / `moa.reference_models[]` / `moa.aggregator` reference the
 *     relay as `provider: custom:apex-nodes.com`. They resolve the credential
 *     THROUGH the registered endpoint and hold no key of their own, so they are
 *     derived and need no sync (verified against the shipped config.yaml).
 *   - `auxiliary.*.api_key` (vision / web_extract / compression / skills_hub) are
 *     BYOK slots with their own `base_url`; they are only managed anchors if a
 *     user points one at the relay, which `pointsAtRelay` already decides — they
 *     need no registry entry to be audited, and are intentionally not written.
 *   - `HERMES_HOME/.env` and the spawn env carry no relay key (verified): the
 *     runtime resolves it from config.yaml only.
 */
export const MANAGED_KEY_ANCHORS: ManagedKeyAnchorKind[] = [
  {
    id: 'model',
    why: 'model.api_key — the credential a chat turn authenticates with (it outranks the environment at client construction). Stale here = every send 401s.',
    matches: (map, baseUrl) =>
      map.path === 'model' && trimSlashes(map.fields.base_url?.value ?? '') === trimSlashes(baseUrl)
  },
  {
    id: 'custom_providers',
    why: "custom_providers[].api_key — the registered endpoint the model picker's live GET /v1/models listing runs on. Stale here = the catalog collapses to the one model config.yaml names. The runtime's own writer (_save_custom_provider) dedups by base_url and refreshes model/api_mode but NEVER api_key, so it can only go stale.",
    matches: (map, baseUrl) => /^custom_providers\[\d+\]$/.test(map.path) && pointsAtRelay(map, baseUrl)
  },
  {
    id: 'providers',
    why: "providers.<slug>.api_key — the v12 dict shape hermes_cli/config.py migrates custom_providers INTO (and then deletes the list). Registered before it is observed in the wild precisely because the previous two rounds of this bug were 'the exit we hadn't looked at yet'.",
    matches: (map, baseUrl) => /^providers\.[^.[\]]+$/.test(map.path) && pointsAtRelay(map, baseUrl)
  }
]

// ── Locating anchors ────────────────────────────────────────────────────────

export interface LocatedAnchor {
  /** Registry entry that claimed this map. */
  kind: string
  /** Concrete path, e.g. `custom_providers[0]`. */
  path: string
  /** Line holding `api_key:`, or -1 when the key line is missing entirely. */
  keyLine: number
  /**
   * Line after which a missing `api_key:` is inserted — always the IDENTITY
   * field (`base_url` / `api` / `name`), never simply the map's last line.
   *
   * The last field of a map may be one that opens a nested block
   * (`model.disabled_providers:`, which the shipped config.yaml really has), and
   * splicing a sibling key between that header and its first item produces
   * invalid YAML — a config.yaml the runtime then refuses to load at all, which
   * is a considerably worse outcome than the stale key we were fixing. The
   * identity field is guaranteed present (it is what `matches` keyed on) and
   * guaranteed a scalar, so inserting after it is always well-formed.
   */
  insertAfter: number
  /** Column at which the inserted key is written. */
  indent: number
  /** Current on-disk value ('' when absent). */
  value: string
}

/** Every registered anchor present in `raw`, in document order. */
export function locateManagedKeyAnchors(raw: string, baseUrl: string): LocatedAnchor[] {
  if (!trimSlashes(baseUrl)) {return []}
  const { maps } = parseYamlMaps(raw)
  const found: LocatedAnchor[] = []

  for (const map of maps) {
    const kind = MANAGED_KEY_ANCHORS.find(anchor => anchor.matches(map, baseUrl))

    if (!kind) {continue}
    const field = map.fields.api_key
    // See LocatedAnchor.insertAfter: anchor the insertion to the scalar this
    // map was IDENTIFIED by, so a nested block elsewhere in the map cannot
    // swallow the new line.
    const identity = map.fields.base_url ?? map.fields.api ?? map.fields.name

    found.push({
      kind: kind.id,
      path: map.path,
      keyLine: field ? field.line : -1,
      insertAfter: field ? field.line : (identity?.line ?? map.lastLine),
      indent: map.indent,
      value: field ? field.value : ''
    })
  }

  return found.sort((a, b) => a.insertAfter - b.insertAfter)
}

// ── The auditor (never reads the registry) ──────────────────────────────────

export interface AuditedAnchor {
  path: string
  /** True when this holder literally carries the expected key. */
  ok: boolean
  /** Masked digest of what it actually holds — safe to log. */
  holds: string
  /** True when no registry entry claims this holder (an anchor nobody wired up). */
  unregistered: boolean
}

export interface AnchorAudit {
  clean: boolean
  holders: AuditedAnchor[]
  stale: string[]
  /** Managed holders no registry entry covers — a class-level regression. */
  unregistered: string[]
}

/**
 * Independently check that EVERY managed relay-key holder in `raw` carries `key`.
 *
 * "Independently" is the entire point: this function does not consult
 * `MANAGED_KEY_ANCHORS`. It flags any map in the document that carries an
 * `api_key` AND points at the relay, wherever it sits in the tree. So it is both
 * the verification step for a write (a writer cannot certify its own blind spot)
 * and the guard that turns the invariant test red when someone adds a fourth
 * place to keep the key without registering it.
 */
export function auditManagedRelayKeyAnchors(raw: string, baseUrl: string, key: string): AnchorAudit {
  const expected = String(key ?? '').trim()
  const { maps } = parseYamlMaps(raw)
  const holders: AuditedAnchor[] = []

  for (const map of maps) {
    const field = map.fields.api_key

    if (!field) {continue}

    if (!pointsAtRelay(map, baseUrl)) {continue}
    holders.push({
      path: map.path,
      ok: field.value === expected,
      holds: maskRelayKey(field.value),
      unregistered: !MANAGED_KEY_ANCHORS.some(anchor => anchor.matches(map, baseUrl))
    })
  }

  const stale = holders.filter(holder => !holder.ok).map(holder => holder.path)
  const unregistered = holders.filter(holder => holder.unregistered).map(holder => holder.path)

  return { clean: stale.length === 0 && unregistered.length === 0, holders, stale, unregistered }
}

// ── Producing the registered endpoint entry ─────────────────────────────────

export interface ManagedProviderEntry {
  name: string
  base_url: string
  api_key: string
  model: string
}

/**
 * THE one renderer of the `custom_providers:` entry that registers the relay.
 *
 * Before hc-602 there were two: the first-run seed emitted a two-space list lead
 * and the boot healer emitted a column-0 one. Both are valid YAML, which is
 * exactly why the divergence survived — and the key patcher only understood one
 * of them. One producer means the shapes cannot drift apart again; the walker
 * above means it would no longer matter if they did.
 */
export function managedCustomProviderEntryYaml(entry: ManagedProviderEntry, indent = 2): string {
  const q = (v: unknown) => JSON.stringify(String(v)) // JSON string == valid YAML double-quoted scalar
  const pad = ' '.repeat(indent)
  const inner = ' '.repeat(indent + 2)

  return (
    `${pad}- name: ${q(entry.name)}\n` +
    `${inner}base_url: ${q(entry.base_url)}\n` +
    `${inner}api_key: ${q(entry.api_key)}\n` +
    `${inner}model: ${entry.model}\n` +
    `${inner}discover_models: true\n`
  )
}

export interface CatalogDiscoverySyncResult {
  changed: boolean
  next: string
  anchors: Array<{ path: string; status: 'updated' | 'inserted' | 'in-sync' }>
}

/**
 * Force live model discovery only on config maps that are provably the managed
 * ApexNodes relay.  Older Windows installs can carry an explicit
 * `discover_models: false` plus a one-model cache; the runtime correctly obeys
 * that user-facing flag and therefore never calls the healthy relay catalog.
 *
 * Identity is intentionally narrower than `pointsAtRelay`: both the relay URL
 * and the current managed key must match, and registered endpoints must also
 * carry the ApexNodes name (or its canonical providers.<slug> path).  A user's
 * own endpoint — including one that explicitly opts out of discovery — is not
 * rewritten merely because it happens to use the same host.
 */
export function syncManagedCatalogDiscoveryYaml(raw: string, baseUrl: string, key: string): CatalogDiscoverySyncResult {
  const source = String(raw ?? '')
  const expectedUrl = trimSlashes(baseUrl)
  const expectedKey = String(key ?? '').trim()
  const idle: CatalogDiscoverySyncResult = { changed: false, next: source, anchors: [] }

  if (!source || !expectedUrl || !expectedKey) {return idle}

  const parsed = parseYamlMaps(source)

  const targets = parsed.maps.filter(map => {
    if (trimSlashes(endpointUrl(map)) !== expectedUrl || map.fields.api_key?.value !== expectedKey) {return false}

    if (map.path === 'model') {
      return (map.fields.provider?.value ?? '').toLowerCase() === 'custom'
    }

    if (/^custom_providers\[\d+\]$/.test(map.path)) {
      return (map.fields.name?.value ?? '').toLowerCase() === MANAGED_PROVIDER_NAME.toLowerCase()
    }

    return /^providers\.apex-nodes(?:-com|\.com)?$/i.test(map.path) ||
      (/^providers\.[^.[\]]+$/.test(map.path) &&
        (map.fields.name?.value ?? '').toLowerCase() === MANAGED_PROVIDER_NAME.toLowerCase())
  })

  if (targets.length === 0) {return idle}

  const eol = source.includes('\r\n') ? '\r\n' : '\n'
  const anchors: CatalogDiscoverySyncResult['anchors'] = []

  for (const map of [...targets].sort((a, b) => b.lastLine - a.lastLine)) {
    const field = map.fields.discover_models

    // Missing is already the runtime's documented `true` default. Do not turn
    // a healthy legacy config into a write + backend reload just to spell out
    // an equivalent value; all newly rendered managed entries are explicit.
    if (!field || !/^(false|no|0)$/i.test(field.value)) {
      anchors.push({ path: map.path, status: 'in-sync' })

      continue
    }

    parsed.lines[field.line] = parsed.lines[field.line].replace(
      /(discover_models:\s*).*$/,
      '$1true'
    )
    anchors.push({ path: map.path, status: 'updated' })
  }

  anchors.reverse()
  const changed = anchors.some(anchor => anchor.status !== 'in-sync')

  return { changed, next: changed ? parsed.lines.join(eol) : source, anchors }
}

// ── Writing (registry-driven, all-or-nothing) ───────────────────────────────

export interface AnchorWriteResult {
  kind: string
  path: string
  status: 'updated' | 'in-sync' | 'inserted'
}

export interface SyncResult {
  changed: boolean
  next: string
  /** At least one registered anchor was addressable. */
  matched: boolean
  /** Back-compat summary of the `model:` anchor. */
  model: 'absent' | 'in-sync' | 'updated'
  /** Back-compat summary of the `custom_providers:` anchors. */
  entries: { matched: number; updated: number }
  anchors: AnchorWriteResult[]
}

/**
 * Rewrite every REGISTERED managed relay key anchor in `raw` to `key`.
 *
 * All-or-nothing by construction: the whole document is rebuilt in memory and
 * returned as one string, so there is no state in which some anchors were
 * written and others were not. A matched anchor that is missing its `api_key:`
 * line gets one inserted (a dropped key line silently falls through to env
 * resolution — the same dead end, harder to see).
 *
 * `matched` is the load-bearing bit the caller cannot get from `changed`:
 * `changed:false` means EITHER "already correct" OR "found nothing to write",
 * and those two need opposite responses (do nothing vs. shout and do NOT mint a
 * key we have just proven we cannot persist).
 */
export function syncManagedRelayKeyYaml(raw: string, baseUrl: string, key: string): SyncResult {
  const source = String(raw ?? '')
  const freshKey = String(key ?? '').trim()

  const idle: SyncResult = {
    changed: false,
    next: source,
    matched: false,
    model: 'absent',
    entries: { matched: 0, updated: 0 },
    anchors: []
  }

  if (!source || !trimSlashes(baseUrl) || !freshKey) {return idle}

  const located = locateManagedKeyAnchors(source, baseUrl)

  if (located.length === 0) {return idle}

  // Parse and rejoin with the file's OWN line ending, so a Windows config.yaml
  // (CRLF — see parseYamlMaps) comes back out as CRLF rather than being quietly
  // converted. `lines` is already \r-free, which is also what lets the rewrite
  // below match: `(.*)$` cannot see past a trailing \r.
  const { lines } = parseYamlMaps(source)
  const eol = source.includes('\r\n') ? '\r\n' : '\n'
  const anchors: AnchorWriteResult[] = []

  // Back-to-front so an inserted line cannot shift a line number we have not
  // visited yet.
  for (const anchor of [...located].reverse()) {
    if (anchor.keyLine >= 0) {
      if (anchor.value === freshKey) {
        anchors.push({ kind: anchor.kind, path: anchor.path, status: 'in-sync' })

        continue
      }

      lines[anchor.keyLine] = lines[anchor.keyLine].replace(
        /(api_key:\s*).*$/,
        `$1${JSON.stringify(freshKey)}`
      )
      anchors.push({ kind: anchor.kind, path: anchor.path, status: 'updated' })

      continue
    }

    lines.splice(anchor.insertAfter + 1, 0, `${' '.repeat(anchor.indent)}api_key: ${JSON.stringify(freshKey)}`)
    anchors.push({ kind: anchor.kind, path: anchor.path, status: 'inserted' })
  }

  anchors.reverse()
  const changed = anchors.some(anchor => anchor.status !== 'in-sync')
  const modelAnchor = anchors.find(anchor => anchor.kind === 'model')
  const entryAnchors = anchors.filter(anchor => anchor.kind !== 'model')

  return {
    changed,
    next: changed ? lines.join(eol) : source,
    matched: true,
    model: modelAnchor ? (modelAnchor.status === 'in-sync' ? 'in-sync' : 'updated') : 'absent',
    entries: {
      matched: entryAnchors.length,
      updated: entryAnchors.filter(anchor => anchor.status !== 'in-sync').length
    },
    anchors
  }
}

// ── Persist + verify ────────────────────────────────────────────────────────

export interface PersistResult {
  ok: boolean
  changed: boolean
  reason: string
  model: string
  entries: { matched: number; updated: number }
  anchors: AnchorWriteResult[]
}

export interface PersistIo {
  read: () => string | null
  write: (next: string) => void
  baseUrl: string
  key: string
}

/**
 * Write `key` into every registered anchor and PROVE it landed by reading the
 * file back and AUDITING it — the hc-595 lesson is not merely that a write
 * nobody verifies is indistinguishable from no write, but that a write verified
 * by its own writer is too. Verification therefore runs
 * `auditManagedRelayKeyAnchors`, which reaches the file by a different route and
 * fails on a stale holder the writer never knew to look for.
 *
 * IO is injected so the whole persist+verify contract is unit-testable without
 * electron; main.ts passes fs against HERMES_HOME.
 */
export function persistRelayKeyToConfigYaml({ read, write, baseUrl, key }: PersistIo): PersistResult {
  const fail = (reason: string, extra: Partial<PersistResult> = {}): PersistResult => ({
    ok: false,
    changed: false,
    reason,
    model: 'absent',
    entries: { matched: 0, updated: 0 },
    anchors: [],
    ...extra
  })

  if (!String(key ?? '').trim() || !String(baseUrl ?? '').trim()) {return fail('no-credential')}

  let raw: string | null

  try {
    raw = read()
  } catch (error: any) {
    return fail(`config-unreadable: ${error && error.message ? error.message : error}`)
  }

  if (typeof raw !== 'string') {return fail('config-missing')}

  const keySync = syncManagedRelayKeyYaml(raw, baseUrl, key)

  // Nothing here is addressable as the managed relay. Writing is pointless and
  // (per the caller's pre-flight) minting a new key would be strictly worse.
  if (!keySync.matched) {return fail('no-managed-anchor')}

  // Once every key anchor carries the expected credential, reconcile the
  // managed catalog policy too.  This is the upgrade/key-rotation path for the
  // Windows stale shape; BYO endpoints are excluded by the narrow identity
  // checks in syncManagedCatalogDiscoveryYaml.
  const catalogSync = syncManagedCatalogDiscoveryYaml(keySync.next, baseUrl, key)

  const sync = {
    ...keySync,
    changed: keySync.changed || catalogSync.changed,
    next: catalogSync.next
  }

  // An unregistered holder means this document keeps the key somewhere the
  // writer does not cover. Writing would leave the file INTERNALLY INCONSISTENT
  // — the precise failure hc-602 exists to make impossible — so refuse before
  // touching anything and name the place.
  const before = auditManagedRelayKeyAnchors(sync.next, baseUrl, key)

  if (before.unregistered.length > 0) {
    return fail(`unregistered-anchor: ${before.unregistered.join(', ')}`, {
      model: sync.model,
      entries: sync.entries,
      anchors: sync.anchors
    })
  }

  if (before.stale.length > 0) {
    return fail(`unwritable-anchor: ${before.stale.join(', ')}`, {
      model: sync.model,
      entries: sync.entries,
      anchors: sync.anchors
    })
  }

  if (sync.changed) {
    try {
      write(sync.next)
    } catch (error: any) {
      return fail(`config-unwritable: ${error && error.message ? error.message : error}`, {
        model: sync.model,
        entries: sync.entries,
        anchors: sync.anchors
      })
    }
  }

  let after: string | null

  try {
    after = read()
  } catch (error: any) {
    return fail(`verify-unreadable: ${error && error.message ? error.message : error}`, {
      changed: sync.changed
    })
  }

  if (typeof after !== 'string') {return fail('verify-unreadable: config-missing', { changed: sync.changed })}

  const audit = auditManagedRelayKeyAnchors(after, baseUrl, key)

  if (audit.holders.length === 0) {
    return fail('verify-failed: no-holder-on-disk', { changed: sync.changed })
  }

  if (!audit.clean) {
    const detail = [...audit.stale, ...audit.unregistered].join(', ')

    return fail(`verify-failed: ${detail}`, { changed: sync.changed })
  }

  return {
    ok: true,
    changed: sync.changed,
    reason: '',
    model: sync.model,
    entries: sync.entries,
    anchors: sync.anchors
  }
}

export { MANAGED_PROVIDER_NAME }
